### ISSUE TITLE
Could not lead textures, not sure why?

### ISSUE THREAD

**Issue by derekcbr** [mrjasonweaver/react-3d-app#17]
index.js:12 Uncaught Could not load ./textures/Metal030_1K_Color.jpg: undefined
handleAsset @ index.js:12
useAsset @ index.js:69
useLoader @ react-three-fiber.esm.js:1607
useTexture @ useTexture.js:8
Scene @ Scene.js:8
renderWithHooks @ react-reconciler.development.js:6412
mountIndeterminateComponent @ react-reconciler.development.js:9238
beginWork @ react-reconciler.development.js:10476
callCallback @ react-reconciler.development.js:12184
invokeGuardedCallbackDev @ react-reconciler.development.js:12233
invokeGuardedCallback @ react-reconciler.development.js:12292
beginWork$1 @ react-reconciler.development.js:16531
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14821
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157

**Comment by mrjasonweaver** [comment]
@derekcbr Should be fixed with #18
